// Retro 95: grey bevels, a navy title bar and a teal desk. The tokens
// here are laid over the Legacy manifest's, and build-theme.mjs writes
// the result to theme.json.
import { iconMap } from './icon-map.mjs';
const FACE = '#c0c0c0';
const LIGHT = '#dfdfdf';
const SHADOW = '#808080';
const NAVY = '#000080';
const TEAL = '#008080';
const SANS = '"OS Retro Sans", "MS Sans Serif", "Microsoft Sans Serif", Tahoma, Arial, sans-serif';
const MONO = '"Courier New", Courier, monospace';
// The era's bevels, as inset shadows: a raised key and the key pressed.
const RAISED = 'inset -1px -1px #000000, inset 1px 1px #ffffff, inset -2px -2px #808080, inset 2px 2px #dfdfdf';
const PRESSED = 'inset -1px -1px #ffffff, inset 1px 1px #000000, inset -2px -2px #dfdfdf, inset 2px 2px #808080';
const WINDOW = 'inset -1px -1px #000000, inset 1px 1px #dfdfdf, inset -2px -2px #808080, inset 2px 2px #ffffff';
const SUNKEN = 'inset -1px -1px #ffffff, inset 1px 1px #808080, inset -2px -2px #dfdfdf, inset 2px 2px #000000';
const SHALLOW = 'inset -1px -1px #ffffff, inset 1px 1px #808080';

export default {
	manifest: {
		manifestVersion: 2,
		id: 'mmtr/retro-95',
		name: 'Retro 95',
		version: '1.0.0',
		author: 'Miguel Torres',
		description: 'Grey bevels, a navy title bar, a teal desk and a taskbar along the bottom: the mid-nineties desktop, pixel for pixel.',
		preview: 'preview.svg',
	},
	fonts: [
		{ family: 'OS Retro Sans', weight: '400', display: 'swap', src: [ 'fonts/os-retro-sans.woff' ] },
		{ family: 'OS Retro Sans', weight: '700', display: 'swap', src: [ 'fonts/os-retro-sans-bold.woff' ] },
	],
	tokens: {
		// --- Type ---
		'--os-font-smoothing': 'antialiased',
		'--os-font': SANS,
		'--os-titlebar-font': SANS,
		'--os-ui-font': SANS,
		'--os-ui-font-mono': MONO,

		// --- Desk ---
		'--os-backstop': TEAL,
		'--os-bg': TEAL,
		'--os-fg': '#ffffff',
		'--os-fg-muted': '#ffffff',
		'--os-desk-ink-light': '#000000',
		'--os-icon-image-size': '32px',
		'--os-icon-label-font-size': '11px',
		'--os-icon-label-radius': '0px',
		'--os-icon-label-padding': '0 2px',
		'--os-icon-label-bg': 'transparent',
		'--os-icon-label-shadow': 'none',
		'--os-icon-glyph-shadow': 'none',
		'--os-icon-hover-bg': 'transparent',
		'--os-tile-fg': '#ffffff',
		'--os-tile-label-color': '#ffffff',
		'--os-tile-label-shadow': 'none',
		'--os-tile-hover-bg': 'transparent',
		'--os-tile-selected-bg': 'transparent',
		'--os-tile-selected-ring-width': '0px',
		'--os-tile-label-font-size': '11px',
		'--os-tile-label-smoothing': 'antialiased',
		'--os-tile-label-weight': '400',
		'--os-tile-label-padding': '0 2px',
		'--os-tile-shortcut-radius': '0px',
		'--os-tile-shortcut-bg': '#ffffff',
		'--os-tile-shortcut-fg': '#000000',
		'--os-tile-shortcut-shadow': '0 0 0 1px #000000',
		'--os-tile-label-selected-bg': NAVY,
		'--os-tile-label-selected-color': '#ffffff',

		// --- Window frame ---
		'--os-window-bg': FACE,
		'--os-window-border': FACE,
		'--os-window-border-width': '3px',
		'--os-window-radius': '0px',
		'--os-window-shadow': 'none',
		'--os-window-shadow-focused': 'none',
		'--os-window-reveal-surface': FACE,
		'--os-folder-window-bg': '#ffffff',
		'--os-resize-color': 'transparent',
		// The close button sits in the top-right corner, flush with the
		// frame: no top corner handle may cover it.
		'--os-resize-top-size': '0px',
		// The era did not dim the windows behind; the title bar says it.
		'--os-fx-darken-brightness': '1',
		'--os-fx-darken-saturate': '1',

		// --- Title bar ---
		'--os-titlebar-bg': SHADOW,
		'--os-titlebar-bg-focused': NAVY,
		'--os-titlebar-color': FACE,
		'--os-titlebar-color-focused': '#ffffff',
		'--os-titlebar-height': '18px',
		'--os-titlebar-padding': '0 2px 0 3px',
		'--os-titlebar-gap': '3px',
		'--os-titlebar-font-size': '11px',
		'--os-titlebar-font-weight': '700',
		'--os-titlebar-btn-width': '16px',
		'--os-titlebar-btn-height': '14px',
		'--os-titlebar-btn-icon-size': '14px',
		'--os-titlebar-btn-press-transform': 'none',
		'--os-titlebar-close-gap': '2px',
		'--os-titlebar-meta-btn-radius': '0px',
		'--os-titlebar-meta-icon-size': '12px',
		'--os-titlebar-activity-display': 'none',
		'--os-titlebar-divider': 'transparent',
		'--os-titlebar-divider-unfocused': 'transparent',
		'--os-titlebar-activity-idle-color': 'transparent',
		'--os-titlebar-controls-gap': '0px',
		'--os-titlebar-btn-color': '#000000',
		// Under the pointer a control lights up and its glyph turns navy;
		// the close button keeps the danger red with a white X.
		'--os-titlebar-btn-color-hover': NAVY,
		'--os-titlebar-btn-bg-hover': LIGHT,
		'--os-titlebar-btn-bg-active': FACE,
		'--os-titlebar-btn-focused-color': '#000000',
		'--os-titlebar-btn-focused-color-hover': NAVY,
		'--os-titlebar-btn-focused-bg-hover': LIGHT,
		'--os-titlebar-btn-focused-bg-active': FACE,
		'--os-titlebar-btn-focused-outline': '#000000',
		'--os-ui-btn-bg': FACE,
		'--os-ui-btn-radius': '0px',

		// --- Tab strip ---
		'--os-tabs-bg': FACE,
		'--os-tabs-bg-unfocused': FACE,
		'--os-tabs-color': '#000000',
		'--os-tabs-active-bg': FACE,
		'--os-tabs-active-color': '#000000',
		'--os-tabs-active-color-muted': '#000000',
		'--os-tabs-rail-opacity': '0',

		// --- Taskbar ---
		'--os-dock-bg': FACE,
		'--os-dock-floating-bg': FACE,
		'--os-dock-border': FACE,
		'--os-dock-floating-border': FACE,
		'--os-dock-floating-border-top': '#ffffff',
		'--os-dock-floating-highlight': LIGHT,
		'--os-dock-floating-shadow': 'transparent',
		'--os-dock-icon-color': '#000000',
		'--os-dock-icon-color-hover': '#000000',
		'--os-dock-item-bg-hover': 'transparent',
		'--os-dock-item-bg-focused': 'transparent',
		'--os-dock-item-outline': '#000000',
		'--os-dock-divider': SHADOW,
		'--os-dock-floating-offset': '0px',
		'--os-dock-floating-width': '100%',
		'--os-dock-floating-max-width': '100%',
		'--os-dock-floating-radius': '0px',
		'--os-dock-floating-padding': '2px 2px 2px 2px',
		'--os-dock-floating-gap': '2px',
		'--os-dock-floating-backdrop': 'none',
		'--os-dock-floating-justify': 'start',
		'--os-dock-floating-track-padding': '0',
		'--os-dock-floating-pinned-padding': '1px 3px',
		'--os-dock-floating-border': FACE,
		'--os-dock-pinned-shadow': SHALLOW,
		'--os-dock-item-size': '24px',
		'--os-dock-item-radius': '0px',
		'--os-dock-item-hover-transform': 'none',
		'--os-dock-item-press-transform': 'none',
		'--os-dock-active-indicator': 'transparent',
		'--os-dock-separator-width': '1px',
		'--os-dock-separator-height': '20px',
		'--os-dock-separator-margin': '3px',
		'--os-dock-separator-bg': SHADOW,
		'--os-dock-separator-shadow': '1px 0 0 #ffffff',
		'--os-dock-exit-radius': '0px',
		'--os-dock-exit-ring': 'transparent',
		'--os-dock-exit-ring-hover': 'transparent',
		'--os-dock-exit-icon': '#000000',
		'--os-dock-exit-gap': '2px',
		'--os-dock-exit-hover-transform': 'none',
		// --- The taskbar renderer ---
		'--os-taskbar-padding': '2px',
		'--os-taskbar-height': '22px',
		'--os-taskbar-gap': '3px',
		'--os-taskbar-font-size': '11px',
		'--os-taskbar-fg': '#000000',
		'--os-taskbar-button-padding': '0 4px',
		'--os-taskbar-button-gap': '3px',
		'--os-taskbar-button-radius': '0px',
		'--os-taskbar-button-bg': FACE,
		'--os-taskbar-button-bg-hover': FACE,
		'--os-taskbar-button-bg-active': FACE,
		'--os-taskbar-button-shadow': RAISED,
		'--os-taskbar-button-shadow-active': PRESSED,
		'--os-taskbar-button-pattern-active': 'repeating-conic-gradient( #ffffff 0 25%, #c0c0c0 0 50% )',
		'--os-taskbar-button-pattern-size': '2px 2px',
		'--os-taskbar-start-weight': '700',
		'--os-taskbar-task-width': '160px',
		'--os-taskbar-icon-size': '16px',
		'--os-taskbar-tray-padding': '0 3px 0 4px',
		'--os-taskbar-tray-radius': '0px',
		'--os-taskbar-tray-shadow': SHALLOW,
		'--os-taskbar-tray-item-size': '20px',
		'--os-taskbar-tray-item-bg-hover': 'transparent',
		'--os-taskbar-focus-outline': '1px dotted #000000',
		'--os-taskbar-focus-offset': '-4px',
		'--os-taskbar-menu-bg': FACE,
		'--os-taskbar-menu-fg': '#000000',
		'--os-taskbar-menu-shadow': WINDOW,
		'--os-taskbar-menu-radius': '0px',
		'--os-taskbar-menu-padding': '3px',
		'--os-taskbar-menu-offset': '0px',
		'--os-taskbar-menu-inset': '2px',
		'--os-taskbar-menu-font-size': '11px',
		'--os-taskbar-menu-item-padding': '4px 16px 4px 6px',
		'--os-taskbar-menu-item-radius': '0px',
		'--os-taskbar-menu-hover-bg': NAVY,
		'--os-taskbar-menu-hover-fg': '#ffffff',
		'--os-taskbar-menu-icon-size': '20px',
		'--os-taskbar-menu-separator': SHADOW,
		'--os-taskbar-menu-separator-shadow': '0 1px 0 #ffffff',
		'--os-taskbar-banner-bg': SHADOW,
		'--os-taskbar-banner-fg': FACE,
		'--os-taskbar-banner-radius': '0px',
		'--os-taskbar-banner-font-size': '20px',
		'--os-tooltip-bg': '#ffffe1',
		'--os-tooltip-fg': '#000000',
		'--os-tooltip-border': '1px solid #000000',
		'--os-tooltip-radius': '0px',
		'--os-tooltip-padding': '1px 4px',
		'--os-tooltip-font-size': '11px',

		// --- Selected rows invert ---
		'--os-ui-tab-fill': NAVY,
		'--os-ui-tab-wash': 'none',
		'--os-ui-tab-bloom-opacity': '0',
		'--os-ui-tab-edge-width': '0px',
		'--os-ui-tab-selected-fg': '#ffffff',

		// --- Dock flyouts (the icon-strip dock): a menu, navy under the pointer ---
		'--os-cn-surface': FACE,
		'--os-cn-fg': '#000000',
		'--os-cn-radius': '0px',
		'--os-cn-shadow': `${ WINDOW }, 1px 1px 0 #000000`,
		'--os-cn-divider': SHADOW,
		'--os-cn-legend': '#000000',
		'--os-cn-backdrop': 'none',
		'--os-cn-spotlight': 'none',
		'--os-cn-sheen': 'none',
		'--os-cn-row-radius': '0px',
		'--os-cn-row-fill': `linear-gradient( ${ NAVY }, ${ NAVY } )`,
		'--os-cn-row-ink': '#ffffff',
		'--os-cn-head-icon-radius': '0px',
		'--os-cn-head-icon-fill': 'none',
		'--os-cn-head-icon-shadow': 'none',
		'--os-cn-orbit': 'currentColor',
		'--os-cn-orbit-halo': 'none',
		'--os-cn-orbit-halo-hover': 'none',
		'--os-cn-beam': '#000000',
		'--os-cn-font': SANS,
		'--os-cn-font-size': '11px',
		'--os-cn-title-size': '11px',
		'--os-cn-title-weight': '700',

		// --- Body palette ---
		'--os-ui-bg': FACE,
		'--os-ui-surface': FACE,
		'--os-ui-surface-elevated': FACE,
		'--os-ui-surface-sunken': '#ffffff',
		'--os-ui-surface-raised': FACE,
		'--os-ui-surface-subtle': 'transparent',
		'--os-ui-bg-subtle': 'transparent',
		'--os-ui-fg': '#000000',
		'--os-ui-fg-muted': '#000000',
		'--os-ui-fg-faint': SHADOW,
		'--os-ui-text-muted': '#000000',
		'--os-ui-border': SHADOW,
		'--os-ui-border-strong': '#000000',
		'--os-ui-hover': 'rgba( 0, 0, 128, 0.08 )',
		'--os-ui-scrim': 'transparent',
		'--os-ui-field-bg': '#ffffff',
		'--os-ui-field-border': SHADOW,
		'--os-ui-field-fg': '#000000',
		'--os-ui-field-radius': '0px',
		'--os-ui-text-field-bg': '#ffffff',
		'--os-ui-text-field-border': '0',
		'--os-ui-text-field-shadow': SUNKEN,
		'--os-ui-focus-ring-field': SUNKEN,
		'--os-ui-field-font-size': '11px',
		'--os-ui-field-font-size-compact': '11px',
		'--os-ui-table-bg': '#ffffff',
		'--os-ui-table-header-bg': FACE,
		'--os-ui-table-font-size': '11px',
		'--os-ui-table-border': FACE,
		'--os-ui-table-row-hover': 'transparent',
		'--os-ui-table-stripe': 'transparent',
		'--os-ui-card-bg': FACE,
		'--os-ui-card-radius': '0px',
		'--os-ui-card-radius-compact': '0px',
		'--os-ui-card-border': SHADOW,
		'--os-ui-card-border-hover': '#000000',
		'--os-ui-card-shadow-hover': 'none',
		'--os-ui-button-border-radius': '0px',
		'--os-ui-button-min-height': '23px',
		'--os-ui-button-padding': '4px 12px',
		'--os-ui-button-bg-hover': FACE,
		'--os-ui-button-bg': FACE,
		'--os-ui-button-fg': '#000000',
		'--os-ui-button-border': '0',
		'--os-ui-button-shadow': RAISED,
		'--os-ui-button-shadow-active': PRESSED,
		'--os-ui-button-press-transform': 'none',
		'--os-ui-button-font-weight': '400',
		'--os-ui-chip-radius': '0px',
		'--os-ui-badge-border-radius': '0px',
		'--os-ui-progress-radius': '0px',
		'--os-ui-progress-fill': NAVY,
		'--os-ui-flyout-bg': FACE,
		'--os-ui-flyout-fg': '#000000',
		'--os-ui-flyout-shadow': '1px 1px 0 #000000',
		'--os-ui-modal-bg': FACE,
		'--os-ui-modal-fg': '#000000',
		'--os-ui-modal-text': '#000000',
		'--os-ui-modal-text-muted': '#000000',
		'--os-ui-modal-surface': FACE,
		'--os-ui-modal-surface-elevated': FACE,
		'--os-ui-modal-field-bg': '#ffffff',
		'--os-ui-modal-border': SHADOW,
		'--os-ui-modal-border-strong': '#000000',
		'--os-ui-modal-hover': 'rgba( 0, 0, 128, 0.08 )',
		'--os-ui-modal-button-bg-hover': FACE,
		'--os-ui-confirm-dialog-bg': FACE,
		'--os-ui-confirm-dialog-fg': '#000000',
		'--os-ui-confirm-dialog-fg-muted': '#000000',
		'--os-ui-context-menu-bg': FACE,
		'--os-ui-context-menu-fg': '#000000',
		'--os-ui-context-menu-fg-muted': SHADOW,
		'--os-ui-context-menu-separator-color': SHADOW,
		'--os-ui-selection-bg': NAVY,
		'--os-ui-selection-fg': '#ffffff',
		'--os-ui-holo-fill': '#ffffff',
		'--os-ui-holo-ink': '#000000',
		'--os-ui-hero-mesh': FACE,

		// --- Widgets on the desk ---
		'--os-ui-color-surface': FACE,
		'--os-ui-color-text': '#000000',
		'--os-ui-color-text-subtle': '#000000',
		'--os-ui-color-border': SHADOW,
		'--os-widgets-add-bg': FACE,
		'--os-widgets-add-bg-hover': FACE,
		'--os-widgets-add-border': '#000000',
		'--os-widget-card-backdrop': 'none',
		'--os-widget-card-border': '0',
		'--os-widget-card-radius': '0px',
		'--os-widget-card-shadow': WINDOW,
		'--os-widget-card-shadow-hover': WINDOW,
	},
	icons: {
		...iconMap(),
		WINDOW_CONTROL_MINIMIZE: { type: 'image', path: 'chrome/glyph-minimize.svg' },
		WINDOW_CONTROL_MAXIMIZE: { type: 'image', path: 'chrome/glyph-maximize.svg' },
		WINDOW_CONTROL_FULLSCREEN: { type: 'image', path: 'chrome/glyph-fullscreen.svg' },
		WINDOW_CONTROL_FULLSCREEN_EXIT: { type: 'image', path: 'chrome/glyph-fullscreen-exit.svg' },
		WINDOW_CONTROL_CLOSE: { type: 'image', path: 'chrome/glyph-close.svg' },
		WINDOW_CONTROL_MENU: { type: 'image', path: 'chrome/glyph-menu.svg' },
		WINDOW_CONTROL_RELOAD: { type: 'image', path: 'chrome/glyph-reload.svg' },
		WINDOW_CONTROL_DETACH: { type: 'image', path: 'chrome/glyph-detach.svg' },
	},
	textures: {
		WINDOW_FRAME: { type: 'border-image', path: 'chrome/frame.svg', slice: '3', width: '3px', repeat: 'stretch' },
		TITLEBAR_BUTTON: { type: 'image', path: 'chrome/button.svg', size: '100% 100%', repeat: 'no-repeat' },
		TITLEBAR_BUTTON_PRESSED: { type: 'image', path: 'chrome/button-pressed.svg' },
		DOCK_ITEM: { type: 'image', path: 'chrome/key.svg', size: '100% 100%', repeat: 'no-repeat' },
		DOCK_ITEM_FOCUSED: { type: 'image', path: 'chrome/key-pressed.svg' },
		DOCK: { type: 'image', path: 'chrome/taskbar.svg', size: 'auto', repeat: 'repeat-x', position: 'left top' },
	},
	wallpapers: {
		teal: { path: 'chrome/desk-teal.svg', label: 'Teal', size: 'auto', repeat: 'repeat', position: 'left top' },
	},
	recommendedOsSettings: {
		windowRadius: 'sharp',
		desktopLayout: 'unified',
		dockPlacement: 'bottom',
		dockSize: 'default',
		adminBarMode: 'hidden',
		windowReveal: 'none',
		wallpaper: 'teal',
		dockRailRenderer: 'taskbar',
		accentColor: NAVY,
		// No Mio and no widgets: neither era had them on the desk.
		navPlacement: { 'os-mio-toggle': 'hidden' },
		widgets: [],
	},
};
